inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  Exclude:
    - 'tasks/release/**/*'
    - 'sample_app/**/*'
    - 'test/dummy/**/*'
    - 'test/fixtures/**/*'
    - 'test/fixtures/**/*'

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/aws-sdk-rails.rb'

Style/GlobalVars:
  AllowedVariables:
    - $VERSION
    - $REPO_ROOT