inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'sample-app/**/*'

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/aws-sdk-rails.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'