inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'tasks/release/**/*'
    - 'sample_app/**/*'
    - 'spec/dummy/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/fixtures/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: Gemfile

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/aws-sdk-rails.rb'

Style/GlobalVars:
  AllowedVariables:
    - $VERSION
    - $REPO_ROOT

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Documentation:
  Exclude:
    - 'lib/aws/rails/notifications.rb'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
