AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'sample-app/**/*'

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Naming/FileName:
  Exclude:
    - 'lib/aws-sdk-rails.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'