language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby

gemfile:
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-6.0.gemfile
  - gemfiles/rails-master.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
  exclude:
    - gemfile: gemfiles/rails-master.gemfile
      rvm: ruby-head
    - gemfile: gemfiles/rails-6.0.gemfile
      rvm: ruby-head

bundler_args: --without docs release
