branches:
  only:
    - master

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.1
  - jruby-9.2

gemfile:
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-6.0.gemfile
  - gemfiles/rails-master.gemfile

jobs:
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
  exclude:
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.3
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.4
    - gemfile: gemfiles/rails-6.0.gemfile
      rvm: 2.3
    - gemfile: gemfiles/rails-6.0.gemfile
      rvm: 2.4
    - gemfile: gemfiles/rails-6.0.gemfile
      rvm: jruby-9.1

bundler_args: --without docs release
