version: '3'

services:
  application-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    environment:
      AWS_SERVICE_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ACTIVE_JOB_QUEUE_URL: http://localstack:4566/000000000000/async-job-queue
      ACTION_MAILER_EMAIL: 'sender@example.com'
    volumes:
      - bundle:/usr/local/bundle
      - ./..:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - localstack
    tty: true
    stdin_open: true
  application-worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["bundle", "exec", "aws_sqs_active_job", "--queue", "default"]
    environment:
      AWS_SERVICE_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ACTIVE_JOB_QUEUE_URL: http://localstack:4566/000000000000/async-job-queue
      ACTION_MAILER_EMAIL: 'sender@example.com'
    volumes:
      - bundle:/usr/local/bundle
      - ./..:/workspace
    tty: true
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
  dynamodb-console:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
    ports:
      - "8001:8001"
    depends_on:
      - localstack

volumes:
  bundle:
    driver: local
